/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppTarefasRouteImport } from './routes/_app.tarefas'
import { Route as AppEmpresasRouteImport } from './routes/_app.empresas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppTarefasIndexRouteImport } from './routes/_app.tarefas.index'
import { Route as AppTarefasRecorrentesRouteImport } from './routes/_app.tarefas.recorrentes'
import { Route as AppRelatoriosIdRouteImport } from './routes/_app.relatorios.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasIndexRoute = AppTarefasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTarefasRoute,
} as any)
const AppTarefasRecorrentesRoute = AppTarefasRecorrentesRouteImport.update({
  id: '/recorrentes',
  path: '/recorrentes',
  getParentRoute: () => AppTarefasRoute,
} as any)
const AppRelatoriosIdRoute = AppRelatoriosIdRouteImport.update({
  id: '/relatorios/$id',
  path: '/relatorios/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresas': typeof AppEmpresasRoute
  '/tarefas': typeof AppTarefasRouteWithChildren
  '/upload': typeof AppUploadRoute
  '/relatorios/$id': typeof AppRelatoriosIdRoute
  '/tarefas/recorrentes': typeof AppTarefasRecorrentesRoute
  '/tarefas/': typeof AppTarefasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresas': typeof AppEmpresasRoute
  '/upload': typeof AppUploadRoute
  '/relatorios/$id': typeof AppRelatoriosIdRoute
  '/tarefas/recorrentes': typeof AppTarefasRecorrentesRoute
  '/tarefas': typeof AppTarefasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empresas': typeof AppEmpresasRoute
  '/_app/tarefas': typeof AppTarefasRouteWithChildren
  '/_app/upload': typeof AppUploadRoute
  '/_app/relatorios/$id': typeof AppRelatoriosIdRoute
  '/_app/tarefas/recorrentes': typeof AppTarefasRecorrentesRoute
  '/_app/tarefas/': typeof AppTarefasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/tarefas'
    | '/upload'
    | '/relatorios/$id'
    | '/tarefas/recorrentes'
    | '/tarefas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/upload'
    | '/relatorios/$id'
    | '/tarefas/recorrentes'
    | '/tarefas'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/empresas'
    | '/_app/tarefas'
    | '/_app/upload'
    | '/_app/relatorios/$id'
    | '/_app/tarefas/recorrentes'
    | '/_app/tarefas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas': {
      id: '/_app/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresas': {
      id: '/_app/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas/': {
      id: '/_app/tarefas/'
      path: '/'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof AppTarefasIndexRouteImport
      parentRoute: typeof AppTarefasRoute
    }
    '/_app/tarefas/recorrentes': {
      id: '/_app/tarefas/recorrentes'
      path: '/recorrentes'
      fullPath: '/tarefas/recorrentes'
      preLoaderRoute: typeof AppTarefasRecorrentesRouteImport
      parentRoute: typeof AppTarefasRoute
    }
    '/_app/relatorios/$id': {
      id: '/_app/relatorios/$id'
      path: '/relatorios/$id'
      fullPath: '/relatorios/$id'
      preLoaderRoute: typeof AppRelatoriosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTarefasRouteChildren {
  AppTarefasRecorrentesRoute: typeof AppTarefasRecorrentesRoute
  AppTarefasIndexRoute: typeof AppTarefasIndexRoute
}

const AppTarefasRouteChildren: AppTarefasRouteChildren = {
  AppTarefasRecorrentesRoute: AppTarefasRecorrentesRoute,
  AppTarefasIndexRoute: AppTarefasIndexRoute,
}

const AppTarefasRouteWithChildren = AppTarefasRoute._addFileChildren(
  AppTarefasRouteChildren,
)

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppTarefasRoute: typeof AppTarefasRouteWithChildren
  AppUploadRoute: typeof AppUploadRoute
  AppRelatoriosIdRoute: typeof AppRelatoriosIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppTarefasRoute: AppTarefasRouteWithChildren,
  AppUploadRoute: AppUploadRoute,
  AppRelatoriosIdRoute: AppRelatoriosIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
